# Form implementation generated from reading ui file '.\day_schedule.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from datetime import datetime


class Ui_DaySchedule(object):
    def setupUi(self, DaySchedule):
        DaySchedule.setObjectName("DaySchedule")
        DaySchedule.resize(335, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(DaySchedule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_d_sched = QtWidgets.QGroupBox(parent=DaySchedule)
        self.gb_d_sched.setObjectName("gb_d_sched")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_d_sched)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tv_day_sched = QtWidgets.QTableView(parent=self.gb_d_sched)
        self.tv_day_sched.setObjectName("tv_day_sched")
        self.tv_day_sched.horizontalHeader().setCascadingSectionResizes(True)
        self.tv_day_sched.horizontalHeader().setStretchLastSection(True)
        self.tv_day_sched.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tv_day_sched)
        self.widget = QtWidgets.QWidget(parent=self.gb_d_sched)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.te_tod = QtWidgets.QTimeEdit(parent=self.widget)
        self.te_tod.setObjectName("te_tod")
        self.gridLayout.addWidget(self.te_tod, 0, 1, 1, 2)
        self.cb_dur = QtWidgets.QComboBox(parent=self.widget)
        self.cb_dur.setObjectName("cb_dur")
        self.gridLayout.addWidget(self.cb_dur, 2, 2, 1, 1)
        self.cb_period = QtWidgets.QComboBox(parent=self.widget)
        self.cb_period.setDuplicatesEnabled(False)
        self.cb_period.setObjectName("cb_period")
        self.gridLayout.addWidget(self.cb_period, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.sb_period = QtWidgets.QSpinBox(parent=self.widget)
        self.sb_period.setObjectName("sb_period")
        self.sb_period.setMaximum(120)
        self.gridLayout.addWidget(self.sb_period, 1, 1, 1, 1)
        self.sb_dur = QtWidgets.QSpinBox(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_dur.sizePolicy().hasHeightForWidth())
        self.sb_dur.setSizePolicy(sizePolicy)
        self.sb_dur.setMinimum(1)
        self.sb_dur.setMaximum(600)
        self.sb_dur.setObjectName("sb_dur")
        self.gridLayout.addWidget(self.sb_dur, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.gb_d_sched)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rb_activate = QtWidgets.QRadioButton(parent=DaySchedule)
        self.rb_activate.setChecked(True)
        self.rb_activate.setObjectName("rb_activate")
        self.horizontalLayout_5.addWidget(self.rb_activate)
        self.rb_inhibit = QtWidgets.QRadioButton(parent=DaySchedule)
        self.rb_inhibit.setChecked(False)
        self.rb_inhibit.setObjectName("rb_inhibit")
        self.horizontalLayout_5.addWidget(self.rb_inhibit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(parent=DaySchedule)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_sched = QtWidgets.QPushButton(parent=DaySchedule)
        self.btn_sched.setObjectName("btn_sched")
        self.horizontalLayout_4.addWidget(self.btn_sched)
        self.btn_unsched = QtWidgets.QPushButton(parent=DaySchedule)
        self.btn_unsched.setObjectName("btn_unsched")
        self.horizontalLayout_4.addWidget(self.btn_unsched)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(DaySchedule)
        QtCore.QMetaObject.connectSlotsByName(DaySchedule)

        # Set line edit input default values
        self.sb_dur.setValue( 10 )
        self.sb_period.setValue( 7 )

        # Set combo box units
        self.cb_dur.addItems( [ 'hour', 'min', 'sec' ] )
        self.cb_dur.setCurrentText( 'min' )
        self.cb_period.addItems( [ 'day', 'hour', 'min', 'sec' ] )
        self.cb_period.setCurrentText( 'day' )

        # Set 24 hour format for time edit
        self.te_tod.setDisplayFormat( 'HH:mm' )

        # Set clock time to current time
        dt = datetime.today()
        self.te_tod.setTime( QtCore.QTime( dt.hour, dt.minute ) )

    def retranslateUi(self, DaySchedule):
        _translate = QtCore.QCoreApplication.translate
        DaySchedule.setWindowTitle(_translate("DaySchedule", "Day Schedule"))
        self.gb_d_sched.setTitle(_translate("DaySchedule", "Schedule"))
        self.cb_dur.setPlaceholderText(_translate("DaySchedule", "min"))
        self.cb_period.setPlaceholderText(_translate("DaySchedule", "hour"))
        self.label_8.setText(_translate("DaySchedule", "Period:"))
        self.label_10.setText(_translate("DaySchedule", "Duration:"))
        self.label_7.setText(_translate("DaySchedule", "Time:"))
        self.rb_activate.setText(_translate("DaySchedule", "Activate"))
        self.rb_inhibit.setText(_translate("DaySchedule", "Inhibit"))
        self.btn_sched.setText(_translate("DaySchedule", "Schedule"))
        self.btn_unsched.setText(_translate("DaySchedule", "Unschedule"))
