name: Build and Upload Release

on:
  release:
    types:
      - created

jobs:
  pyinstaller-win-build:
    permissions:
      contents: write
    runs-on: windows-latest
    name: Create Windows Executable
    steps:
      - name: Build executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: 'remote_controller.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'remote_controller'
          options: --onefile, --windowed, --name "Remote Controller"

      - name: Get the release upload URL
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            return context.payload.release.upload_url;

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.result }}
          asset_path: ./dist/remote_controller.exe
          asset_name: remote_controller.exe
          asset_content_type: application/octet-stream

  #pyinstaller-mac-build:
  #  needs: pyinstaller-win-build # wait for windows to be done then checkout and push on top
  #  permissions:
  #    contents: write
  #  runs-on: macos-13
  #  name: Create Mac OS Executable
  #  steps:
  #    - uses: actions/checkout@v4
  #    - run: pip install protobuf
  #    - run: pip install PyQt6
  #    - uses: Martin005/pyinstaller-action@v1.2.0
  #      with:
  #        spec: 'remote_gardener_gui.py'
  #        upload_exe_with_name: 'remote_gardener_mac'
  #        options: --noconfirm --onefile, --windowed, --name "Remote Gardener Mac OS",
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: remote_gardener_mac
  #        path: ./dist
  #    - uses: actions/download-artifact@v4
  #      with:
  #        name: remote_gardener_mac
  #        path: ./dist
  #    - uses: stefanzweifel/git-auto-commit-action@v4
  #      with:
  #        commit_message: Automated Change
  #        branch: main
  #        commit_options: '--no-verify --signoff'
  #        commit_author: Author <actions@github.com>
  #        status_options: '--untracked-files=no'
  #        skip_dirty_check: true
